// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebApp.Data;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260128050458_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "authentication");
                });

            modelBuilder.Entity("WebApp.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLdapUser")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "authentication");
                });

            modelBuilder.Entity("WebApp.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Areas_Codigo");

                    b.ToTable("Areas", "planta");
                });

            modelBuilder.Entity("WebApp.Models.Boton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("DepartamentoOperadorId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaUltimaActivacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Botones_Codigo");

                    b.HasIndex("DepartamentoOperadorId");

                    b.ToTable("Botones", "planta");
                });

            modelBuilder.Entity("WebApp.Models.DepartamentoOperador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_DepartamentosOperador_Nombre");

                    b.ToTable("DepartamentosOperador", "operadores");
                });

            modelBuilder.Entity("WebApp.Models.Estacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("LineaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Estaciones_Codigo");

                    b.HasIndex("LineaId");

                    b.ToTable("Estaciones", "planta");
                });

            modelBuilder.Entity("WebApp.Models.Linea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("AreaId")
                        .HasColumnType("integer");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Lineas_Codigo");

                    b.ToTable("Lineas", "planta");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.Botonera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("DireccionIP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("DireccionIP")
                        .IsUnique()
                        .HasDatabaseName("IX_Botoneras_DireccionIP");

                    b.HasIndex("MaquinaId");

                    b.HasIndex("NumeroSerie")
                        .IsUnique()
                        .HasDatabaseName("IX_Botoneras_NumeroSerie");

                    b.ToTable("Botoneras", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.CatalogoFalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Severidad")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TiempoEstimadoSolucionMinutos")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_CatalogoFallas_Codigo");

                    b.ToTable("CatalogoFallas", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.ComentarioParoBotonera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("RegistroParoBotoneraId")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RegistroParoBotoneraId")
                        .HasDatabaseName("IX_ComentariosParoBotonera_RegistroParoBotoneraId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ComentariosParoBotonera_UserId");

                    b.ToTable("ComentariosParoBotonera", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.CorridaProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ContadorNOKFinal")
                        .HasColumnType("bigint");

                    b.Property<long>("ContadorNOKInicial")
                        .HasColumnType("bigint");

                    b.Property<long>("ContadorOKFinal")
                        .HasColumnType("bigint");

                    b.Property<long>("ContadorOKInicial")
                        .HasColumnType("bigint");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroLecturas")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroResetsNOK")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroResetsOK")
                        .HasColumnType("integer");

                    b.Property<long>("ProduccionNOK")
                        .HasColumnType("bigint");

                    b.Property<long>("ProduccionOK")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<long>("UltimoContadorNOK")
                        .HasColumnType("bigint");

                    b.Property<long>("UltimoContadorOK")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("MaquinaId", "Estado")
                        .HasDatabaseName("IX_CorridasProduccion_MaquinaId_Estado");

                    b.HasIndex("MaquinaId", "FechaInicio")
                        .HasDatabaseName("IX_CorridasProduccion_MaquinaId_FechaInicio");

                    b.ToTable("CorridasProduccion", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.Dispositivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("CodigoDispositivo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaUltimaLectura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoDispositivo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UltimoContador")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MaquinaId", "CodigoDispositivo")
                        .IsUnique()
                        .HasDatabaseName("IX_Dispositivos_MaquinaId_CodigoDispositivo");

                    b.ToTable("Dispositivos", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.HistorialCambioParo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CampoModificado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("FechaModificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Motivo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RegistroParoId")
                        .HasColumnType("integer");

                    b.Property<string>("UsuarioModifica")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ValorAnterior")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ValorNuevo")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("RegistroParoId")
                        .HasDatabaseName("IX_HistorialCambiosParos_RegistroParoId");

                    b.ToTable("HistorialCambiosParos", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.LecturaContador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ContadorNOK")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContadorNOKAnterior")
                        .HasColumnType("bigint");

                    b.Property<long>("ContadorOK")
                        .HasColumnType("bigint");

                    b.Property<long?>("ContadorOKAnterior")
                        .HasColumnType("bigint");

                    b.Property<int>("CorridaId")
                        .HasColumnType("integer");

                    b.Property<long>("DiferenciaNOK")
                        .HasColumnType("bigint");

                    b.Property<long>("DiferenciaOK")
                        .HasColumnType("bigint");

                    b.Property<bool>("EsResetNOK")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsResetOK")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaHoraLectura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<long>("ProduccionNOK")
                        .HasColumnType("bigint");

                    b.Property<long>("ProduccionOK")
                        .HasColumnType("bigint");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("CorridaId", "FechaHoraLectura")
                        .HasDatabaseName("IX_LecturasContador_CorridaId_Fecha");

                    b.HasIndex("MaquinaId", "FechaHoraLectura")
                        .HasDatabaseName("IX_LecturasContador_MaquinaId_Fecha");

                    b.ToTable("LecturasContador", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.MetricasMaquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CalidadPorcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Cerrada")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DisponibilidadPorcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("OeePorcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RendimientoPorcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TiempoDisponibleMinutos")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoParoMinutos")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoProduccionMinutos")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadesBuenas")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadesDefectuosas")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadesProducidas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("MaquinaId", "FechaInicio")
                        .HasDatabaseName("IX_MetricasMaquina_MaquinaId_FechaInicio");

                    b.ToTable("MetricasMaquina", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TiempoCicloSegundos")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadesPorCiclo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Productos_Codigo");

                    b.ToTable("Productos", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.RegistroContador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ContadorNOK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ContadorOK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("FechaHoraLectura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModeloId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModeloId");

                    b.HasIndex("MaquinaId", "FechaHoraLectura")
                        .HasDatabaseName("IX_RegistrosContadores_MaquinaId_FechaHoraLectura");

                    b.ToTable("RegistrosContadores", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.RegistroFalla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccionesTomadas")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("CatalogoFallaId")
                        .HasColumnType("integer");

                    b.Property<int?>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaHoraAtencion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHoraDeteccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaHoraResolucion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<int?>("TecnicoAsignadoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoFallaId")
                        .HasDatabaseName("IX_RegistrosFallas_CatalogoFallaId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_RegistrosFallas_Estado");

                    b.HasIndex("TecnicoAsignadoId");

                    b.HasIndex("MaquinaId", "FechaHoraDeteccion")
                        .HasDatabaseName("IX_RegistrosFallas_MaquinaId_FechaHoraDeteccion");

                    b.ToTable("RegistrosFallas", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.RegistroParo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CausaParoId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<bool>("EsMicroParo")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("FechaAtencion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHoraInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<int?>("MetricasMaquinaId")
                        .HasColumnType("integer");

                    b.Property<int?>("OperadorResponsableId")
                        .HasColumnType("integer");

                    b.Property<int?>("OperadorSolucionaId")
                        .HasColumnType("integer");

                    b.Property<int?>("SesionProduccionId")
                        .HasColumnType("integer");

                    b.Property<string>("Solucion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_RegistrosParos_Estado");

                    b.HasIndex("MetricasMaquinaId");

                    b.HasIndex("OperadorResponsableId");

                    b.HasIndex("OperadorSolucionaId");

                    b.HasIndex("SesionProduccionId");

                    b.HasIndex("MaquinaId", "FechaHoraInicio")
                        .HasDatabaseName("IX_RegistrosParos_MaquinaId_FechaHoraInicio");

                    b.ToTable("RegistrosParos", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.RegistroParoBotonera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BotonId")
                        .HasColumnType("integer");

                    b.Property<int>("BotoneraId")
                        .HasColumnType("integer");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("integer");

                    b.Property<int?>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Abierto");

                    b.Property<DateTime?>("FechaHoraFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHoraInicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<int?>("OperadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BotonId");

                    b.HasIndex("BotoneraId");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_RegistrosParoBotonera_Estado");

                    b.HasIndex("OperadorId");

                    b.HasIndex("MaquinaId", "FechaHoraInicio")
                        .HasDatabaseName("IX_RegistrosParoBotonera_MaquinaId_FechaHoraInicio");

                    b.ToTable("RegistrosParoBotonera", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.RegistroProduccionHora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("OperadorId")
                        .HasColumnType("integer");

                    b.Property<int>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<int>("SesionProduccionId")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoParoMinutos")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoProduccionMinutos")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadesBuenas")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadesDefectuosas")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadesProducidas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OperadorId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("SesionProduccionId", "FechaHora")
                        .IsUnique()
                        .HasDatabaseName("IX_RegistrosProduccionHora_SesionProduccionId_FechaHora");

                    b.ToTable("RegistrosProduccionHora", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.SesionProduccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CalidadPorcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("Cerrada")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DisponibilidadPorcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaquinaId")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("OeePorcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("RendimientoPorcentaje")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("TiempoDisponibleMinutos")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoParoMinutos")
                        .HasColumnType("integer");

                    b.Property<int>("TiempoProduccionMinutos")
                        .HasColumnType("integer");

                    b.Property<int>("TurnoId")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadesBuenas")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadesDefectuosas")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadesProducidas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TurnoId");

                    b.HasIndex("MaquinaId", "FechaInicio")
                        .HasDatabaseName("IX_SesionesProduccion_MaquinaId_FechaInicio");

                    b.ToTable("SesionesProduccion", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.Turno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("IX_Turnos_Nombre");

                    b.ToTable("Turnos", "linealytics");
                });

            modelBuilder.Entity("WebApp.Models.Maquina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EstacionId")
                        .HasColumnType("integer");

                    b.Property<string>("Fabricante")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Maquinas_Codigo");

                    b.HasIndex("EstacionId");

                    b.HasIndex("NumeroSerie")
                        .IsUnique()
                        .HasDatabaseName("IX_Maquinas_NumeroSerie");

                    b.ToTable("Maquinas", "planta");
                });

            modelBuilder.Entity("WebApp.Models.MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Icono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Orden")
                        .HasDatabaseName("IX_MenuItems_Orden");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_MenuItems_ParentId");

                    b.ToTable("MenuItems", "authentication");
                });

            modelBuilder.Entity("WebApp.Models.MenuRolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("MenuItemId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("IX_MenuRolePermissions_MenuItemId_RoleId");

                    b.ToTable("MenuRolePermissions", "authentication");
                });

            modelBuilder.Entity("WebApp.Models.Modelo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_Modelos_Codigo");

                    b.ToTable("Modelos", "planta");
                });

            modelBuilder.Entity("WebApp.Models.Operador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoPinHashed")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroEmpleado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroEmpleado")
                        .IsUnique()
                        .HasDatabaseName("IX_Operadores_NumeroEmpleado");

                    b.ToTable("Operadores", "operadores");
                });

            modelBuilder.Entity("WebApp.Models.OperadorDepartamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoOperadorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("OperadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartamentoOperadorId");

                    b.HasIndex("OperadorId", "DepartamentoOperadorId")
                        .IsUnique()
                        .HasDatabaseName("IX_OperadorDepartamentos_OperadorId_DepartamentoOperadorId");

                    b.ToTable("OperadorDepartamentos", "operadores");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApp.Models.Boton", b =>
                {
                    b.HasOne("WebApp.Models.DepartamentoOperador", "DepartamentoOperador")
                        .WithMany()
                        .HasForeignKey("DepartamentoOperadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepartamentoOperador");
                });

            modelBuilder.Entity("WebApp.Models.Estacion", b =>
                {
                    b.HasOne("WebApp.Models.Linea", "Linea")
                        .WithMany("Estaciones")
                        .HasForeignKey("LineaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Linea");
                });

            modelBuilder.Entity("WebApp.Models.Linea", b =>
                {
                    b.HasOne("WebApp.Models.Area", "Area")
                        .WithMany("Lineas")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.Botonera", b =>
                {
                    b.HasOne("WebApp.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.ComentarioParoBotonera", b =>
                {
                    b.HasOne("WebApp.Models.Linealytics.RegistroParoBotonera", "RegistroParoBotonera")
                        .WithMany("Comentarios")
                        .HasForeignKey("RegistroParoBotoneraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegistroParoBotonera");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.CorridaProduccion", b =>
                {
                    b.HasOne("WebApp.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Linealytics.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquina");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.Dispositivo", b =>
                {
                    b.HasOne("WebApp.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquina");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.HistorialCambioParo", b =>
                {
                    b.HasOne("WebApp.Models.Linealytics.RegistroParo", "RegistroParo")
                        .WithMany("HistorialCambios")
                        .HasForeignKey("RegistroParoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistroParo");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.LecturaContador", b =>
                {
                    b.HasOne("WebApp.Models.Linealytics.CorridaProduccion", "Corrida")
                        .WithMany("Lecturas")
                        .HasForeignKey("CorridaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Linealytics.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Corrida");

                    b.Navigation("Maquina");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.MetricasMaquina", b =>
                {
                    b.HasOne("WebApp.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Linealytics.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApp.Models.Linealytics.Turno", "Turno")
                        .WithMany()
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquina");

                    b.Navigation("Producto");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.RegistroContador", b =>
                {
                    b.HasOne("WebApp.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Modelo", "Modelo")
                        .WithMany()
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Maquina");

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.RegistroFalla", b =>
                {
                    b.HasOne("WebApp.Models.Linealytics.CatalogoFalla", "CatalogoFalla")
                        .WithMany("RegistrosFallas")
                        .HasForeignKey("CatalogoFallaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Operador", "TecnicoAsignado")
                        .WithMany()
                        .HasForeignKey("TecnicoAsignadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CatalogoFalla");

                    b.Navigation("Maquina");

                    b.Navigation("TecnicoAsignado");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.RegistroParo", b =>
                {
                    b.HasOne("WebApp.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Linealytics.MetricasMaquina", "MetricasMaquina")
                        .WithMany("RegistrosParos")
                        .HasForeignKey("MetricasMaquinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApp.Models.Operador", "OperadorResponsable")
                        .WithMany()
                        .HasForeignKey("OperadorResponsableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApp.Models.Operador", "OperadorSoluciona")
                        .WithMany()
                        .HasForeignKey("OperadorSolucionaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApp.Models.Linealytics.SesionProduccion", null)
                        .WithMany("RegistrosParos")
                        .HasForeignKey("SesionProduccionId");

                    b.Navigation("Maquina");

                    b.Navigation("MetricasMaquina");

                    b.Navigation("OperadorResponsable");

                    b.Navigation("OperadorSoluciona");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.RegistroParoBotonera", b =>
                {
                    b.HasOne("WebApp.Models.Boton", "Boton")
                        .WithMany()
                        .HasForeignKey("BotonId");

                    b.HasOne("WebApp.Models.Linealytics.Botonera", "Botonera")
                        .WithMany()
                        .HasForeignKey("BotoneraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.DepartamentoOperador", "DepartamentoOperador")
                        .WithMany()
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Operador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId");

                    b.Navigation("Boton");

                    b.Navigation("Botonera");

                    b.Navigation("DepartamentoOperador");

                    b.Navigation("Maquina");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.RegistroProduccionHora", b =>
                {
                    b.HasOne("WebApp.Models.Operador", "Operador")
                        .WithMany()
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApp.Models.Linealytics.Producto", "Producto")
                        .WithMany("RegistrosProduccionHora")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Linealytics.SesionProduccion", "SesionProduccion")
                        .WithMany("RegistrosProduccionHora")
                        .HasForeignKey("SesionProduccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Operador");

                    b.Navigation("Producto");

                    b.Navigation("SesionProduccion");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.SesionProduccion", b =>
                {
                    b.HasOne("WebApp.Models.Maquina", "Maquina")
                        .WithMany()
                        .HasForeignKey("MaquinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Linealytics.Producto", "Producto")
                        .WithMany("SesionesProduccion")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApp.Models.Linealytics.Turno", "Turno")
                        .WithMany("SesionesProduccion")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Maquina");

                    b.Navigation("Producto");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("WebApp.Models.Maquina", b =>
                {
                    b.HasOne("WebApp.Models.Estacion", "Estacion")
                        .WithMany("Maquinas")
                        .HasForeignKey("EstacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estacion");
                });

            modelBuilder.Entity("WebApp.Models.MenuItem", b =>
                {
                    b.HasOne("WebApp.Models.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("WebApp.Models.MenuRolePermission", b =>
                {
                    b.HasOne("WebApp.Models.MenuItem", "MenuItem")
                        .WithMany("MenuRolePermissions")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("WebApp.Models.OperadorDepartamento", b =>
                {
                    b.HasOne("WebApp.Models.DepartamentoOperador", "DepartamentoOperador")
                        .WithMany("OperadorDepartamentos")
                        .HasForeignKey("DepartamentoOperadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApp.Models.Operador", "Operador")
                        .WithMany("OperadorDepartamentos")
                        .HasForeignKey("OperadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DepartamentoOperador");

                    b.Navigation("Operador");
                });

            modelBuilder.Entity("WebApp.Models.Area", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("WebApp.Models.DepartamentoOperador", b =>
                {
                    b.Navigation("OperadorDepartamentos");
                });

            modelBuilder.Entity("WebApp.Models.Estacion", b =>
                {
                    b.Navigation("Maquinas");
                });

            modelBuilder.Entity("WebApp.Models.Linea", b =>
                {
                    b.Navigation("Estaciones");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.CatalogoFalla", b =>
                {
                    b.Navigation("RegistrosFallas");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.CorridaProduccion", b =>
                {
                    b.Navigation("Lecturas");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.MetricasMaquina", b =>
                {
                    b.Navigation("RegistrosParos");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.Producto", b =>
                {
                    b.Navigation("RegistrosProduccionHora");

                    b.Navigation("SesionesProduccion");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.RegistroParo", b =>
                {
                    b.Navigation("HistorialCambios");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.RegistroParoBotonera", b =>
                {
                    b.Navigation("Comentarios");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.SesionProduccion", b =>
                {
                    b.Navigation("RegistrosParos");

                    b.Navigation("RegistrosProduccionHora");
                });

            modelBuilder.Entity("WebApp.Models.Linealytics.Turno", b =>
                {
                    b.Navigation("SesionesProduccion");
                });

            modelBuilder.Entity("WebApp.Models.MenuItem", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("MenuRolePermissions");
                });

            modelBuilder.Entity("WebApp.Models.Operador", b =>
                {
                    b.Navigation("OperadorDepartamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
